#Book eng
class Book:
    def __init__(self, title, price, author, publisher, genre, publicationYear, code, available, series, translator, summary, description):
        self.title = title
        self.price = price
        self.author = author  #نويسنده
        self.publisher = publisher  #انشاراتي
        self.genre = genre #ژانر
        self.publicationYear = publicationYear  #سال انتشار
        self.code = code
        self.available = available  #موجودي
        self.series = series
        self.translator = translator #مترجم
        self.summary = summary  #خلاصه کتاب
        self.description = description #توضيح کتاب
    def __repr__(self):
        return f'here is a short summary of "{self.title}":\n{self.summary}'
    def __str__(self):
        return f'"{self.title}" is written by "{self.author}".'
    def get_summary(self):
        return f'here is a short summary of "{self.title}":\n{self.summary}'
    def get_price(self):
        return f'this book is {self.price} toman.'
    def get_genre(self):
        return f'{self.available} genres are {self.genre}.'
    def get_available(self):
        return f'{self.available} copies of "{self.title}" with the code ({self.code}) is available.'
    def get_publisher(self):
        return f'"{self.title}" publisher is "{self.publisher}".'
    def get_series(self):
        return f'"{self.title}" is from "{self.series}" series.'
    def get_desc (self):
        return f'{self.title} description:\n{self.description}'
    def full_info(self):
        print(f'Book title: {self.title}')
        print(f'Series: {self.series}')
        print(f'Written by author: {self.author} - Translated by: {self.translator}')
        print(f'Genre: {self.genre}')
        print(f'Publisher and year of publication: {self.publisher} - year of {self.publicationYear}')
        print(f'Short summary of "{self.title}":')
        print(f'{self.summary}')
        print(f'"{self.title}" with code *{self.code}* is available in {self.available} copies.')
        print(f'price: {self.price} toman')

Tokyo_Ghoul = Book('Tokyo Ghoul', 120000, 'Sui Ishida', 'Shueisha', ['Manga','Dark fantasy','Supernatural','thriller'], 2011, '001', 6, 'Tokyo Ghoul', 'Viz Media', 'Ken Kaneki is an ordinary college student until a violent encounter turns him into the first half-human half-ghoul hybrid. Trapped between two worlds, he must survive Ghoul turf wars, learn more about Ghoul society and master his new powers.', 'This book contains 224 pages and is translated into English and at the moment only Volume 1 of the serie is available.')
You_are_Not_Listening = Book("You're Not Listening", 108000, 'Kate Murphy', 'Nashremun(نشرمون)', ['Psychology','Self Help'], 1401, '002', 10, '-', 'Ali Musavi', 'When was the last time you listened to someone, or someone really listened to you?\n"If you’re like most people, you don’t listen as often or as well as you’d like. There’s no one better qualified than a talented journalist to introduce you to the right mindset and skillset―and this book does it with science and humor."\n-Adam Grant', 'This book contains 250 pages and is translated into Farsi')
Jane_Eyre_1 = Book('Jane Eyre #1', 270000, 'Charlotte Brontë,', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical'], 1397, '003', 3, 'Classic Romance', 'Nushin Ebrahimi', "Story of orphaned Jane Eyre, who grows up in the home of her heartless aunt, enduring loneliness and cruelty. This troubled childhood strengthens Jane's natural independence and spirit - which prove necessary when she finds employment as a governess to the young ward of Byronic, brooding Mr Rochester. As her feelings for Rochester develop, Jane gradually uncovers Thornfield Hall's terrible secret, forcing her to make a choice.", 'This book contains 479 pages and is translated into Farsi.')
The_Dark_Side_Of_The_Light = Book('The Dark Side Of The Light', 118000, 'Debbie Ford', 'Atisa(آتيسا)', ['Psychology','Self Help','Philosophy'], 1400, '004', 8, '-', 'Abdullah Salahi', "We know the shadow by many names: alter ego, lower self, the dark twin, repressed self, id. Carl Jung once said that the shadow 'is the person you would rather not be.' But even if you choose to hide your dark side, it will still cast a shadow, according to author Debbie Ford. Rather than reject the seemingly undesirable parts of ourselves, Ford offers advice on how to confront our shadows. Only by owning every aspect of yourself can you achieve harmony and 'let your own light shine.'", 'This book contains 240 pages and is translated into Farsi.')
Jane_Eyre_2 = Book('Jane Eyre #2', 270000, 'Charlotte Brontë,', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical'], 1398, '005', 2, 'Classic Romance', 'Nushin Ebrahimi', 'Continuation of the previous volume.', 'This book contains 512 pages and is translated into Farsi.')
Atomic_Habits = Book('Atomic Habits', 147250, 'James Clear', 'Novin(نوين)', ['Self Help','Personal Development','Business','Philosophy'], 1402, '006', 5, '-', 'Hadi Bahmani', "If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights.", 'This book contains 273 pages and is translated into Farsi.')
The_Girl_With_All_The_Gifts_1 = Book('The Girl With All The Gifts #1', 321300, 'M.R. Carey', 'Bazh(باژ)', ['Horror','Fiction','Science Fiction','Zombies','Post Apocalyptic','Fantasy','Thriller','Adult'], 1397, '007', 0, 'The Girl With All The Gifts', 'Behnam Hajizade', "Every morning, Melanie waits in her cell to be collected for class. When they come for her, Sergeant Parks keeps his gun pointing at her while two of his people strap her into the wheelchair. She thinks they don't like her. She jokes that she won't bite, but they don't laugh. Melanie loves school. She loves learning about spelling and sums and the world outside the classroom and the children's cells. She tells her favorite teacher all the things she'll do when she grows up. Melanie doesn't know why this makes Miss Justineau look sad.", 'This book contains 308 pages and is translated into Farsi also the second volume is available.')
The_Girl_With_All_The_Gifts_2 = Book('The Girl With All The Gifts #2', 270000, 'M.R. Carey', 'Bazh(باژ)', ['Horror','Fiction','Science Fiction','Zombies','Post Apocalyptic','Fantasy','Thriller','Adult'], 1397, '008', 3, 'The Girl With All The Gifts', 'Behnam Hajizade', 'Continuation of the previous volume.', 'This book contains 270 pages and is translated into Farsi.\nNOTE: This book also has a movie!')
One_Piece = Book('One Piece', 120000, 'Eiichiro Oda', 'Shueisha', ['Manga','Adventure','Fantasy','Fiction','Pirates'], 1997, '009', 14, 'One Piece', 'Viz Media', 'Monkey D. Luffy, whose main ambition is to become a pirate. Eating the Gum-Gum Fruit gives him strange powers but also invokes the fruits curse: anybody who consumes it can never learn to swim. Nevertheless, Monkey and his crewmate Roronoa Zoro, master of the three-sword fighting style, sail the Seven Seas of swashbuckling adventure in search of the elusive treasure "One Piece."', 'This book contains 205 pages and is translated into English. This series has 109 valumes to this day and is still ongoing!\n(but unfortunatly right now only volume 1 is available)')
Sence_And_Sensibility = Book('Sence And Sensibility', 270000, 'Jane Austen', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical','Literature'], 1397, '010', 7, 'Classic Romance', 'Shahrzad Lolachi', "Marianne Dashwood wears her heart on her sleeve, and when she falls in love with the dashing but unsuitable John Willoughby she ignores her sister Elinor's warning that her impulsive behaviour leaves her open to gossip and innuendo. Meanwhile Elinor, always sensitive to social convention, is struggling to conceal her own romantic disappointment, even from those closest to her. Through their parallel experience of love—and its threatened loss—the sisters learn that sense must mix with sensibility if they are to find personal happiness in a society where status and money govern the rules of love.", 'This book contains 432 pages and is translated into Farsi.')
Lord_Loss = Book('Lord Loss', 63750, 'Darren Shan', 'Ghadyani(قدياني)', ['Horror','Fantasy','Fiction','Paranormal','Demons','Supernatural','Magic'], 1395, '011', 4, 'Demonata series', 'Farzane Karimi', 'Grubbs Grady has stiff red hair and is a little big for his age, which means he can get into R-rated movies. He hates history and loves bacon, rats, and playing tricks on his squeamish older sister. When he opts out of a family weekend trip, he never guesses that he is about to take a terrifying journey into darkness. Hungry demons and howling werewolves haunt his waking nightmares... and threaten his life.', 'This book contains 336 pages and is translated into Farsi. There are also 8 other books available for this series but for now they are not available for purchace.')
The_Odyssey = Book('The Odyssey', 160000, 'Homer', 'Behzad(بهزاد)', ['Classics','Fiction','Poetry','Mythology','Literature','Adventure','Historical Fiction'], 1398, '012', 6, '-', 'Saeed Nafisi', "If the Iliad is the world's greatest war epic, then the Odyssey is literature's grandest evocation of everyman's journey though life. Odysseus' reliance on his wit and wiliness for survival in his encounters with divine and natural forces, during his ten-year voyage home to Ithaca after the Trojan War, is at once a timeless human story and an individual test of moral endurance.", 'This book contains 416 pages and is translated into Farsi.')
Animal_Farm = Book('Animal Farm', 136000, 'George Orwell', 'Ofogh(افق)', ['Classics','Fiction','Dystopia','Fantasy','Politics','Literature'], 1398, '013', 10, '-', 'Shahrzad Lolachi', 'A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.', 'This book contains 106 pages and is translated into Farsi.')
Desiree_1 = Book('Desiree #1', 272000, 'Annemarie Selinko', 'Ofogh(افق)', ['Historical Fiction','Fiction','Historical','Classics','Romance','France','Historical Romance','Roman','Sweden'], 1396, '014', 8, 'Classic Romance', 'Keyvan Abidi', "To be young, in France, and in love: fourteen year old Desiree can't believe her good fortune. Her fiance, a dashing and ambitious Napoleon Bonaparte, is poised for battlefield success, and no longer will she be just a French merchant's daughter. She could not have known the twisting path her role in history would take, nearly breaking her vibrant heart but sweeping her to a life rich in passion and desire.", 'This book contains 560 pages and is translated into Farsi. Volume 2 is also available.')
Desiree_2 = Book('Desiree #2', 246500, 'Annemarie Selinko', 'Ofogh(افق)', ['Historical Fiction','Fiction','Historical','Classics','Romance','France','Historical Romance','Roman','Sweden'], 1396, '015', 8, 'Classic Romance', 'Keyvan Abidi', 'Continuation of the previous volume.', 'This book contains 506 pages and is translated into Farsi.')
Six_Of_Crows = Book('Six Of Crows', 306000, 'Leigh Bardugo', 'Bazh(باژ)', ['Fantasy','Fiction','Adventure','Magic','High Fantasy'], 1400, '016', 5, 'Six of Crows', 'Maryam Rafiee',"Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone. . . ., A convict with a thirst for revenge, A sharpshooter who can’t walk away from a wager, A runaway with a privileged past, A spy known as the Wraith, A Heartrender using her magic to survive the slums, A thief with a gift for unlikely escapes. Six dangerous outcasts. One impossible heist. Kaz’s crew is the only thing that might stand between the world and destruction—if they don’t kill each other first.", 'This book contains 516 pages and is translated into Farsi. Volume 2 is also available, Check out "Crooked Kingdom".')
Crooked_Kingdom = Book('Crooked Kingdom', 374000, 'Leigh Bardugo', 'Bazh(باژ)', ['Fantasy','Fiction','Adventure','Magic','High Fantasy'], 1401, '017', 5, 'Six of Crows', 'Maryam Rafiee','Continuation of the previous volume.', 'This book contains 600 pages and is translated into Farsi. Make sure to read "Six of Crows" first.')
Daddy_Long_Legs = Book('Daddy Long Legs', 193000, 'Jean Webster', 'Ofogh(افق)', ['Classics','Fiction','Romance','Childrens','Humor','Historical Fiction','Historical'], 1398, '018', 3, 'Classic Romance', 'Mohsen Solaimani', 'the adventures of an orphan named Judy Abbott, whose letters to her anonymous male benefactor trace her development as an independent thinker and writer.', 'This book contains 296 pages and is translated into Farsi. Volume 2 is also available, Check out "Dear Enemy".')
Dear_Enemy = Book('Dear Enemy', 280500, 'Jean Webster', 'Ofogh(افق)', ['Classics','Fiction','Romance','Childrens','Humor','Historical Fiction','Historical'], 1399, '019', 3, 'Classic Romance', 'Parinaz Shahin', "Like the previous book, also told in letters, follows the progress of Judy's former orphanage now run by her friend Sallie McBride, who struggles to give her young charges hope and a new life. Full of irrepressible female characters that both recall Alcott's Jo March and anticipate the popular heroines of contemporary literature.", 'This book contains 530 pages and is translated into Farsi. Make sure to read "Daddy Long Legs" first.')
Throne_Of_Glass = Book('Throne Of Glass', 207000, 'Sarah J. Maas', 'Bazh(باژ)', ['Fantasy','Romance','Fiction','Magic','High Fantasy','Adventure'], 1397, '020', 15, 'Throne of Glass', 'Afshin Ardeshiri', "In a land without magic, where the king rules with an iron hand, an assassin is summoned to the castle. She comes not to kill the king, but to win her freedom. If she defeats twenty-three killers, thieves, and warriors in a competition, she is released from prison to serve as the king's champion. Her name is Celaena Sardothien. The Crown Prince will provoke her. The Captain of the Guard will protect her. But something evil dwells in the castle of glass—and it's there to kill. When her competitors start dying one by one, Celaena's fight for freedom becomes a fight for survival, and a desperate quest to root out the evil before it destroys her world.", 'This book contains 495 pages and is translated into Farsi. For this serie only the first valume is avsilable at the moment.')
The_Anne_Of_Green_Gables = Book('The Anne Of Green Gables', 125000, 'L.M. Montgomery', 'Ghadyani(قدياني)', ['Classics','Fiction','Historical Fiction','Childrens','Historical','Canada'], 1400, '021', 6, 'Anne of Green Gables', 'Sara Ghadyani', 'Anne Shirley, an eleven-year-old orphan, has arrived in this verdant corner of Prince Edward Island only to discover that the Cuthberts—elderly Matthew and his stern sister, Marilla—want to adopt a boy, not a feisty redheaded girl. But before they can send her back, Anne—who simply must have more scope for her imagination and a real home—wins them over completely.', 'This book contains 496 pages and is translated into Farsi. For this serie only the first valume is avsilable at the moment.')
Shahname = Book('Shahname', 2000000, 'Ferdosi', 'Sokhan(سخن)', ['Poetry','Classics','History','Iran','Mythology','Literature','Epic','Historical'], 1402, '022', 5, '-', ' = ', 'The national epic of Persia. This prodigious narrative, composed by the poet Ferdowsi between the years 980 and 1010, tells the story of pre-Islamic Iran, beginning in the mythic time of Creation and continuing forward to the Arab invasion in the seventh century.', 'This book contains 2121 pages.') 

Books = [Tokyo_Ghoul, Jane_Eyre_2, Atomic_Habits, The_Girl_With_All_The_Gifts_1, The_Girl_With_All_The_Gifts_2, One_Piece, Sence_And_Sensibility, Lord_Loss, The_Odyssey, Animal_Farm, Desiree_1, Desiree_2, Six_Of_Crows, Crooked_Kingdom, Daddy_Long_Legs, Dear_Enemy, Throne_Of_Glass, The_Anne_Of_Green_Gables, Shahname]

books = [
Book('Tokyo Ghoul Volume 1', 120000, 'Sui Ishida', 'Shueisha', ['Manga','Dark fantasy','Supernatural','thriller'], 2011, '001', 6, 'Tokyo Ghoul', 'Viz Media', 'Ken Kaneki is an ordinary college student until a violent encounter turns him into the first half-human half-ghoul hybrid. Trapped between two worlds, he must survive Ghoul turf wars, learn more about Ghoul society and master his new powers.', 'This book contains 224 pages and is translated into English and at the moment only Volume 1 of the serie is available.')
,Book("You're Not Listening", 108000, 'Kate Murphy', 'Nashremun(نشرمون)', ['Psychology','Self Help'], 1401, '002', 10, '-', 'Ali Musavi', 'When was the last time you listened to someone, or someone really listened to you?\n"If you’re like most people, you don’t listen as often or as well as you’d like. There’s no one better qualified than a talented journalist to introduce you to the right mindset and skillset―and this book does it with science and humor."\n-Adam Grant', 'This book contains 250 pages and is translated into Farsi')
,Book('Jane Eyre #1', 270000, 'Charlotte Brontë,', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical'], 1397, '003', 3, 'Classic Romance', 'Nushin Ebrahimi', "Story of orphaned Jane Eyre, who grows up in the home of her heartless aunt, enduring loneliness and cruelty. This troubled childhood strengthens Jane's natural independence and spirit - which prove necessary when she finds employment as a governess to the young ward of Byronic, brooding Mr Rochester. As her feelings for Rochester develop, Jane gradually uncovers Thornfield Hall's terrible secret, forcing her to make a choice.", 'This book contains 479 pages and is translated into Farsi.')
,Book('The Dark Side Of The Light', 118000, 'Debbie Ford', 'Atisa(آتيسا)', ['Psychology','Self Help','Philosophy'], 1400, '004', 8, '-', 'Abdullah Salahi', "We know the shadow by many names: alter ego, lower self, the dark twin, repressed self, id. Carl Jung once said that the shadow 'is the person you would rather not be.' But even if you choose to hide your dark side, it will still cast a shadow, according to author Debbie Ford. Rather than reject the seemingly undesirable parts of ourselves, Ford offers advice on how to confront our shadows. Only by owning every aspect of yourself can you achieve harmony and 'let your own light shine.'", 'This book contains 240 pages and is translated into Farsi.')
,Book('Jane Eyre #2', 270000, 'Charlotte Brontë,', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical'], 1398, '005', 2, 'Classic Romance', 'Nushin Ebrahimi', 'Continuation of the previous volume.', 'This book contains 512 pages and is translated into Farsi.')
,Book('Atomic Habits', 147250, 'James Clear', 'Novin(نوين)', ['Self Help','Personal Development','Business','Philosophy'], 1402, '006', 5, '-', 'Hadi Bahmani', "If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights.", 'This book contains 273 pages and is translated into Farsi.')
,Book('The Girl With All The Gifts #1', 321300, 'M.R. Carey', 'Bazh(باژ)', ['Horror','Fiction','Science Fiction','Zombies','Post Apocalyptic','Fantasy','Thriller','Adult'], 1397, '007', 0, 'The Girl With All The Gifts', 'Behnam Hajizade', "Every morning, Melanie waits in her cell to be collected for class. When they come for her, Sergeant Parks keeps his gun pointing at her while two of his people strap her into the wheelchair. She thinks they don't like her. She jokes that she won't bite, but they don't laugh. Melanie loves school. She loves learning about spelling and sums and the world outside the classroom and the children's cells. She tells her favorite teacher all the things she'll do when she grows up. Melanie doesn't know why this makes Miss Justineau look sad.", 'This book contains 308 pages and is translated into Farsi also the second volume is available.')
,Book('The Girl With All The Gifts #2', 270000, 'M.R. Carey', 'Bazh(باژ)', ['Horror','Fiction','Science Fiction','Zombies','Post Apocalyptic','Fantasy','Thriller','Adult'], 1397, '008', 3, 'The Girl With All The Gifts', 'Behnam Hajizade', 'Continuation of the previous volume.', 'This book contains 270 pages and is translated into Farsi.\nNOTE: This book also has a movie!')
,Book('One Piece Volume 1', 120000, 'Eiichiro Oda', 'Shueisha', ['Manga','Adventure','Fantasy','Fiction','Pirates'], 1997, '009', 14, 'One Piece', 'Viz Media', 'Monkey D. Luffy, whose main ambition is to become a pirate. Eating the Gum-Gum Fruit gives him strange powers but also invokes the fruits curse: anybody who consumes it can never learn to swim. Nevertheless, Monkey and his crewmate Roronoa Zoro, master of the three-sword fighting style, sail the Seven Seas of swashbuckling adventure in search of the elusive treasure "One Piece."', 'This book contains 205 pages and is translated into English. This series has 109 valumes to this day and is still ongoing!\n(but unfortunatly right now only volume 1 is available)')
,Book('Sence And Sensibility', 270000, 'Jane Austen', 'Ofogh(افق)', ['Classic','Fiction','Romance','Historical Fiction','Literature','Historical','Literature'], 1397, '010', 7, 'Classic Romance', 'Shahrzad Lolachi', "Marianne Dashwood wears her heart on her sleeve, and when she falls in love with the dashing but unsuitable John Willoughby she ignores her sister Elinor's warning that her impulsive behaviour leaves her open to gossip and innuendo. Meanwhile Elinor, always sensitive to social convention, is struggling to conceal her own romantic disappointment, even from those closest to her. Through their parallel experience of love—and its threatened loss—the sisters learn that sense must mix with sensibility if they are to find personal happiness in a society where status and money govern the rules of love.", 'This book contains 432 pages and is translated into Farsi.')
,Book('Lord Loss', 63750, 'Darren Shan', 'Ghadyani(قدياني)', ['Horror','Fantasy','Fiction','Paranormal','Demons','Supernatural','Magic'], 1395, '011', 4, 'Demonata series', 'Farzane Karimi', 'Grubbs Grady has stiff red hair and is a little big for his age, which means he can get into R-rated movies. He hates history and loves bacon, rats, and playing tricks on his squeamish older sister. When he opts out of a family weekend trip, he never guesses that he is about to take a terrifying journey into darkness. Hungry demons and howling werewolves haunt his waking nightmares... and threaten his life.', 'This book contains 336 pages and is translated into Farsi. There are also 8 other books available for this series but for now they are not available for purchace.')
,Book('The Odyssey', 160000, 'Homer', 'Behzad(بهزاد)', ['Classics','Fiction','Poetry','Mythology','Literature','Adventure','Historical Fiction'], 1398, '012', 6, '-', 'Saeed Nafisi', "If the Iliad is the world's greatest war epic, then the Odyssey is literature's grandest evocation of everyman's journey though life. Odysseus' reliance on his wit and wiliness for survival in his encounters with divine and natural forces, during his ten-year voyage home to Ithaca after the Trojan War, is at once a timeless human story and an individual test of moral endurance.", 'This book contains 416 pages and is translated into Farsi.')
,Book('Animal Farm', 136000, 'George Orwell', 'Ofogh(افق)', ['Classics','Fiction','Dystopia','Fantasy','Politics','Literature'], 1398, '013', 10, '-', 'Shahrzad Lolachi', 'A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.', 'This book contains 106 pages and is translated into Farsi.')
,Book('Desiree #1', 272000, 'Annemarie Selinko', 'Ofogh(افق)', ['Historical Fiction','Fiction','Historical','Classics','Romance','France','Historical Romance','Roman','Sweden'], 1396, '014', 8, 'Classic Romance', 'Keyvan Abidi', "To be young, in France, and in love: fourteen year old Desiree can't believe her good fortune. Her fiance, a dashing and ambitious Napoleon Bonaparte, is poised for battlefield success, and no longer will she be just a French merchant's daughter. She could not have known the twisting path her role in history would take, nearly breaking her vibrant heart but sweeping her to a life rich in passion and desire.", 'This book contains 560 pages and is translated into Farsi. Volume 2 is also available.')
,Book('Desiree #2', 246500, 'Annemarie Selinko', 'Ofogh(افق)', ['Historical Fiction','Fiction','Historical','Classics','Romance','France','Historical Romance','Roman','Sweden'], 1396, '015', 8, 'Classic Romance', 'Keyvan Abidi', 'Continuation of the previous volume.', 'This book contains 506 pages and is translated into Farsi.')
,Book('Six Of Crows', 306000, 'Leigh Bardugo', 'Bazh(باژ)', ['Fantasy','Fiction','Adventure','Magic','High Fantasy'], 1400, '016', 5, 'Six of Crows', 'Maryam Rafiee',"Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone. . . ., A convict with a thirst for revenge, A sharpshooter who can’t walk away from a wager, A runaway with a privileged past, A spy known as the Wraith, A Heartrender using her magic to survive the slums, A thief with a gift for unlikely escapes. Six dangerous outcasts. One impossible heist. Kaz’s crew is the only thing that might stand between the world and destruction—if they don’t kill each other first.", 'This book contains 516 pages and is translated into Farsi. Volume 2 is also available, Check out "Crooked Kingdom".')
,Book('Crooked Kingdom', 374000, 'Leigh Bardugo', 'Bazh(باژ)', ['Fantasy','Fiction','Adventure','Magic','High Fantasy'], 1401, '017', 5, 'Six of Crows', 'Maryam Rafiee','Continuation of the previous volume.', 'This book contains 600 pages and is translated into Farsi. Make sure to read "Six of Crows" first.')
,Book('Daddy Long Legs', 193000, 'Jean Webster', 'Ofogh(افق)', ['Classics','Fiction','Romance','Childrens','Humor','Historical Fiction','Historical'], 1398, '018', 3, 'Classic Romance', 'Mohsen Solaimani', 'the adventures of an orphan named Judy Abbott, whose letters to her anonymous male benefactor trace her development as an independent thinker and writer.', 'This book contains 296 pages and is translated into Farsi. Volume 2 is also available, Check out "Dear Enemy".')
,Book('Dear Enemy', 280500, 'Jean Webster', 'Ofogh(افق)', ['Classics','Fiction','Romance','Childrens','Humor','Historical Fiction','Historical'], 1399, '019', 3, 'Classic Romance', 'Parinaz Shahin', "Like the previous book, also told in letters, follows the progress of Judy's former orphanage now run by her friend Sallie McBride, who struggles to give her young charges hope and a new life. Full of irrepressible female characters that both recall Alcott's Jo March and anticipate the popular heroines of contemporary literature.", 'This book contains 530 pages and is translated into Farsi. Make sure to read "Daddy Long Legs" first.')
,Book('Throne Of Glass', 207000, 'Sarah J. Maas', 'Bazh(باژ)', ['Fantasy','Romance','Fiction','Magic','High Fantasy','Adventure'], 1397, '020', 15, 'Throne of Glass', 'Afshin Ardeshiri', "In a land without magic, where the king rules with an iron hand, an assassin is summoned to the castle. She comes not to kill the king, but to win her freedom. If she defeats twenty-three killers, thieves, and warriors in a competition, she is released from prison to serve as the king's champion. Her name is Celaena Sardothien. The Crown Prince will provoke her. The Captain of the Guard will protect her. But something evil dwells in the castle of glass—and it's there to kill. When her competitors start dying one by one, Celaena's fight for freedom becomes a fight for survival, and a desperate quest to root out the evil before it destroys her world.", 'This book contains 495 pages and is translated into Farsi. For this serie only the first valume is avsilable at the moment.')
,Book('The Anne Of Green Gables', 125000, 'L.M. Montgomery', 'Ghadyani(قدياني)', ['Classics','Fiction','Historical Fiction','Childrens','Historical','Canada'], 1400, '021', 6, 'Anne of Green Gables', 'Sara Ghadyani', 'Anne Shirley, an eleven-year-old orphan, has arrived in this verdant corner of Prince Edward Island only to discover that the Cuthberts—elderly Matthew and his stern sister, Marilla—want to adopt a boy, not a feisty redheaded girl. But before they can send her back, Anne—who simply must have more scope for her imagination and a real home—wins them over completely.', 'This book contains 496 pages and is translated into Farsi. For this serie only the first valume is avsilable at the moment.')
,Book('Shahname', 2000000, 'Ferdosi', 'Sokhan(سخن)', ['Poetry','Classics','History','Iran','Mythology','Literature','Epic','Historical'], 1402, '022', 5, '-', ' = ', 'The national epic of Persia. This prodigious narrative, composed by the poet Ferdowsi between the years 980 and 1010, tells the story of pre-Islamic Iran, beginning in the mythic time of Creation and continuing forward to the Arab invasion in the seventh century.', 'This book contains 2121 pages.')]
